services:
  dev:
    container_name: quyca-dev
    network_mode: host
    restart: on-failure
    build:
      network: host
      context: .
      dockerfile: Dockerfile
      target: development
    image: colav/quyca-dev:dev
    volumes:
      - .:/app
    working_dir: /app
    environment:
      PYTHONPATH: /quyca
    entrypoint: [ "poetry", "run", "python", "./quyca/app.py" ]


  prod:
    container_name: quyca-prod
    network_mode: host
    restart: on-failure
    build:
      network: host
      context: .
      dockerfile: Dockerfile
      target: production
    image: colav/quyca-prod:latest
    volumes:
      - .:/app
    working_dir: /app
    environment:
      PYTHONPATH: /quyca
    entrypoint:
      - poetry
      - run
      - gunicorn
      - --bind
      - 0.0.0.0:${APP_PORT}
      - --workers
      - "12"
      - --timeout
      - "600"
      - app:create_app()
      - --access-logfile
      - "-"
      - --error-logfile
      - "-"

  local:
    container_name: quyca-local
    network_mode: host
    restart: on-failure
    build:
      network: host
      context: .
      dockerfile: Dockerfile
      target: local
    image: colav/quyca-local:local
    volumes:
      - .:/app
    working_dir: /app
    environment:
      PYTHONPATH: /quyca
    entrypoint: [ "poetry", "run", "python", "./quyca/app.py" ]
